// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4Ub3zNd1d28OLgx62ibpynl9nJJ9RUGA',
    appId: '1:843569560650:web:a08068dfa096d6e73d3ab3',
    messagingSenderId: '843569560650',
    projectId: 'ooriba-s3-intern',
    authDomain: 'ooriba-s3-intern.firebaseapp.com',
    storageBucket: 'ooriba-s3-intern.appspot.com',
    measurementId: 'G-46DNJ14XFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJHP_4OhHw-912pThMjcb3RY0feAiaLdw',
    appId: '1:843569560650:android:256320fa0746ea943d3ab3',
    messagingSenderId: '843569560650',
    projectId: 'ooriba-s3-intern',
    storageBucket: 'ooriba-s3-intern.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2j8KYOT3xfGwedmsjXZg_lNOCxFR7z-Q',
    appId: '1:843569560650:ios:a42e8cce532e730c3d3ab3',
    messagingSenderId: '843569560650',
    projectId: 'ooriba-s3-intern',
    storageBucket: 'ooriba-s3-intern.appspot.com',
    iosBundleId: 'com.example.oorib3S3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2j8KYOT3xfGwedmsjXZg_lNOCxFR7z-Q',
    appId: '1:843569560650:ios:a42e8cce532e730c3d3ab3',
    messagingSenderId: '843569560650',
    projectId: 'ooriba-s3-intern',
    storageBucket: 'ooriba-s3-intern.appspot.com',
    iosBundleId: 'com.example.oorib3S3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4Ub3zNd1d28OLgx62ibpynl9nJJ9RUGA',
    appId: '1:843569560650:web:ecae9f0b77d3ef8c3d3ab3',
    messagingSenderId: '843569560650',
    projectId: 'ooriba-s3-intern',
    authDomain: 'ooriba-s3-intern.firebaseapp.com',
    storageBucket: 'ooriba-s3-intern.appspot.com',
    measurementId: 'G-9VSYK32YP7',
  );

}